### ISSUE TITLE
Double scaling of homemade powerlaw rheology

### ISSUE THREAD

**Issue by mthielma** [tduretz/MDOODZ7.0#124]
When a "homemade" powerlaw of the form eta = eta0 * exp(-Q/n/R/T) * Eii^(1/n - 1) is used via prescribing eta0 in the input file (e.g. in Shrinking.txt), the resulting prefactor A will be wrong, which will then result in viscosities that are way too low. The reason for this is that eta0 is scaled in InputOutput.c, but then the resulting Apwl is again scaled in FlowLaws.c. 
One could now either remove the scaling in InputOutput.c or rescale eta0 in FlowLaws.c
This may also be true for eps0 and tau0, but I have not looked at that.

**Comment by tduretz** [comment]
Thanks for picking this one up. Does it mean that resulting viscosity if a function of scaling? Like you get the viscosity you expect when all scales are scaled to 1 but not when they are different from 1?

**Comment by mthielma** [comment]
I just tried with ViscousInclusion using a powerlaw rheology and yes, the resulting viscosity is a function of the scaling viscosity (looking at both the output from the simulation and the output files).

**Comment by tduretz** [comment]
OK, perfect. Then it makes a test case to try one your fixes. Do you mind making a PR with one of your fixes?

**Comment by mthielma** [comment]
Yup, I'll prepare something.

**Comment by PYamato** [comment]
Original Shrinking model used "real" pwl rheologies (Anorthite dry from Rybacki and Dresen) and I checked the obtained viscosity value for homogeneous model... so I think it is fine for this setup... Anaïs is running model with "Homemade" law right now. I'm gonna check it...

**Comment by PYamato** [comment]
Ok, after a simple check, it seems that things are correct at least in MD6... We did simulations for an homogeneous material for different values of n => the obtained values for viscosity that are in agreement with what is expected. And if we change the scaling value for eta, results remain the same...

**Comment by mthielma** [comment]
I also had no issues with MD6.

**Comment by tduretz** [comment]
Ok, thanks for having checked! I guess we may simply incorporate your fix.
